### ISSUE TITLE
Failed start command

### ISSUE THREAD

**Issue by lilliputten** [bem/create-bem-react-app#39]
After installing and creating the application, an error occurs during the execution of the `npm start` command in `node_modules/@bem/sdk.config/index.js:extendConfigsPathByLayer()`.
```log
        config.levels && config.levels.forEach(level => {
                                       ^
TypeError: config.levels.forEach is not a function
    at configs.forEach.config (my-app/node_modules/@bem/sdk.config/index.js:412:40)
    at Array.forEach (native)
    at extendConfigsPathByLayer (my-app/node_modules/@bem/sdk.config/index.js:411:13)
    at BemConfig.configs (my-app/node_modules/@bem/sdk.config/index.js:55:23)
    at BemConfig.getSync (my-app/node_modules/@bem/sdk.config/index.js:258:23)
    at BemConfig.moduleSync (my-app/node_modules/@bem/sdk.config/index.js:361:24)

    at Object.<anonymous> (my-app/node_modules/bem-react-scripts/config/paths.js:17:31)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)```
```

The variable `config.levels` is expected as an array whereas when it's a hash:

```javascript
{ 'src/components': { scheme: 'nested', default: true } }
```

In `.bemrc` change the parameter `levels` to become an array:

```javascript
    "levels": [
        {
            "path": "src/components",
            "scheme": "nested",
            "default": true
        }
    ],
```

Next see an error:

```log
Error: Cannot find module 'babel-preset-es2015'
```

Install it:

```shell
npm i -D babel-preset-es2015
```

Run `npm start` again. `localhost:3000` opens in browser. Got in the browser window:
```log
Failed to compile.

Error in ./src/index.js
Module not found: Can't resolve './componentsAppApp.css' in 'my-app/src'

 @ multi ./~/react-dev-utils/webpackHotDevClient.js ./~/bem-react-scripts/config/polyfills.js ./src/index.js
```

Got in the console the foloowing:
```log
Failed to compile.

Error in ./src/index.js
Module not found: Can't resolve './componentsAppApp.css' in 'my-app/src'

 @ multi ./~/react-dev-utils/webpackHotDevClient.js ./~/bem-react-scripts/config/polyfills.js ./src/index.js

Error in ./src/index.js
Module not found: Can't resolve './componentsPagePage.css' in 'my-app/src'

 @ multi ./~/react-dev-utils/webpackHotDevClient.js ./~/bem-react-scripts/config/polyfills.js ./src/index.js

Error in ./src/index.js
Module not found: Can't resolve './componentsAppApp.js' in 'my-app/src'

 @ multi ./~/react-dev-utils/webpackHotDevClient.js ./~/bem-react-scripts/config/polyfills.js ./src/index.js
```

Versions:
```shell
$ npm view create-bem-react-app version
0.0.3

$ npm -v
5.5.1

$ node -v
v6.10.0
```

Running on Win10.

**Comment by awinogradov** [comment]
@Yeti-or can you help to understand the problem with bem-config?

**Comment by basilred** [comment]
I have exactly the same problem. macOS, node 9.3.0, npm 5.5.1.

**Comment by lilliputten** [comment]
Still using 0.1.2. The solution has not yet been found?

**Comment by awinogradov** [comment]
The current project is deprecated since we have https://github.com/bem/bem-react-boilerplate. Please try it and write some feedback for us ;)

**Comment by lilliputten** [comment]
@awinogradov Yes, thank you! This works fine.

**Comment by innabelaya** [comment]
here's [the fix](https://github.com/bem/create-bem-react-app/pull/41) anyway
